name: build tor
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  schedule:
    - cron: '1 9 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install docker
        run: >
          sudo apt update -y -qqq;
          sudo apt autoremove --purge -y needrestart || true;
          sudo apt install -y bash wget openssl;
          sudo ln -svf bash /bin/sh;
          sudo /bin/bash scripts/clean-os.sh;
          sudo /bin/rm -fr /tmp/*;
          sudo /bin/bash scripts/install-docker.sh

      - name: Build tor al9
        run: |
          sudo /bin/bash run-build-al9.sh
          sudo /bin/systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/* /mnt/docker-data/*

      - name: Build tor al8
        run: |
          sudo /bin/bash run-build-al8.sh
          sudo /bin/systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/* /mnt/docker-data/*

      - name: Build tor ub2204
        run: |
          sudo /bin/bash run-build-ub2204.sh
          sudo /bin/systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/* /mnt/docker-data/*

      - name: Build tor ub2004
        run: |
          sudo /bin/bash run-build-ub2004.sh
          sudo /bin/systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/* /mnt/docker-data/*

      - name: Generate release tag env
        run: |
          _release_ver="$(/bin/ls -1 /tmp/_output_assets/_output/tor-*_amd64.tar.xz | grep -i 'el9_amd64.tar.xz$' | sed -e 's|.*tor-||g' -e 's|-[1-9].*||g' | head -1)"
          echo "_release_ver=${_release_ver}" >> $GITHUB_ENV

      - name: Upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env._release_ver }}
          files: /tmp/_output_assets/_output/*

      - name: Delete old release tag env
        run: |
          sed -e "/^_release_ver=/d" -i $GITHUB_ENV
